services:
  movex-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: movex-backend
    container_name: movex-backend
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - movex-network

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: movex-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - movex-network

  redis:
    image: redis:8
    container_name: movex-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - movex-network

volumes:
  postgres_data:
  redis_data:

networks:
  movex-network:
    name: movex-network
    driver: bridge
