"""add ride pricing fields

Revision ID: 9d0760b16978
Revises: dc331456d3dc
Create Date: 2026-09-21 20:07:23.678606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0760b16978'
down_revision: Union[str, Sequence[str], None] = 'dc331456d3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('distance_meters', sa.DOUBLE_PRECISION(), nullable=False))
    op.add_column('rides', sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('rides', sa.Column('currency', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'currency')
    op.drop_column('rides', 'price')
    op.drop_column('rides', 'distance_meters')
    # ### end Alembic commands ###
